# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_visitor_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='current_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
